### ISSUE TITLE
APIs and Elastic Search (copied from meetup.com)

### ISSUE THREAD

**Issue by adz** [AdelaideRB/meetups#1]
I'd love to hear a talk on building APIs with authentication in Ruby to be consumed by mobile apps (I've heard good things about Grape), and if anyone has experience using ElasticSearch in ruby / rails, that'd probably make for a great talk. Just some ideas, maybe for the meetup after installfest, assuming anyone actually has experience in these things.
http://www.meetup.com/adelaiderb/events/222866270/

**Comment by rahult** [comment]
We have written a couple of API's using [Active Model Serializer](https://github.com/rails-api/active_model_serializers) and [JSON API](https://github.com/cerebris/jsonapi-resources) specificially for JS Frontends and mobile devices.

**Comment by chris-teague** [comment]
@rahult will you have time to do this presentation at the next meetup? Doesn't have to be long, i.e. 15mins is fine

EDIT: Just the API for JS Frontends, not ElasticSearch :)

**Comment by rahult** [comment]
@chris-teague I am back Thursday and then need to finish office work so will be very time pressed. I can do it next month for sure.

**Comment by chris-teague** [comment]
@rahult no problemo, will hit you up for next month
