### ISSUE TITLE
Profiling Rails Apps

### ISSUE THREAD

**Issue by rahult** [AdelaideRB/meetups#2]
I will interested in someone going through techniques to profile Rails Applications

Tools https://github.com/MiniProfiler/rack-mini-profiler

**Comment by blaknite** [comment]
I have spent the better part of the last six months using rack-mini-profiler to profile my website. I have been using it to identify opportunities to optimise SQL queries, modify schemas, add indexes and/or add caching. I am more than happy to present my methods and experiences. There's some excellent gains to be had!

**Comment by adz** [comment]
Would be great @blaknite ! I've used it a little when we had serious issues caused by new features, but would love to hear your experience and tips...

**Comment by rahult** [comment]
This would be awesome @blaknite

**Comment by blaknite** [comment]
Sweet as. Just let me know when and I'll get it done.

**Comment by adz** [comment]
Presented at November 2015
