### ISSUE TITLE
Middleman

### ISSUE THREAD

**Issue by phoozle** [AdelaideRB/meetups#4]
I'm happy to do a small talk on Middleman (static site generator) in the near future.

Having used Jekyll in the past, Middleman offers greater flexibility, Rails like features and is overall a far less opinionated framework.

If there is time I will also cover deploying to Bitballoon and how you can utilise "Magic Forms" to give your site a database backend.

**Comment by adz** [comment]
Sounds great! Could you do June 7?
Otherwise let us know which month after that?

**Comment by phoozle** [comment]
@adz Sure I can do June 7. Looking forward to it

**Comment by adz** [comment]
Awesome, we'll book you in :)

BTW -- what was your last name? We have a few different Matthews !

**Comment by phoozle** [comment]
@adz Matthew Croall, cheers
